#!/usr/bin/env bash
set -euo pipefail

# OpenGrokBot — assemble a self-hosted Grok Bot alternative from OpenClaw + your own model key.
#
# Usage:
#   ./setup.sh                     interactive
#   XAI_API_KEY=... ./setup.sh     non-interactive (also: ANTHROPIC_API_KEY / OPENAI_API_KEY)
#
# What it does:
#   1. Installs OpenClaw via the official installer (skips if already installed)
#   2. Writes an openclaw.json with three teammate agents + agent-to-agent messaging
#   3. Installs the teammate workspaces (Scout / Sorter / Ticker)
#   4. NEVER overwrites an existing config — generates a merge file instead
#
# It does NOT run interactive onboarding for you; it prints the exact next commands.

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OC_DIR="${OPENCLAW_CONFIG_DIR:-$HOME/.openclaw}"
CONFIG="$OC_DIR/openclaw.json"
GEN_DIR="$REPO_DIR/generated"

say()  { printf '\033[1;36m[OpenGrokBot]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[OpenGrokBot]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[OpenGrokBot]\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- 0. platform
case "$(uname -s)" in
  Darwin|Linux) ;;
  *) die "This script supports macOS and Linux. On Windows, run it inside WSL2." ;;
esac
command -v curl >/dev/null 2>&1 || die "curl is required."

# ---------------------------------------------------------------- 1. openclaw
if command -v openclaw >/dev/null 2>&1; then
  say "OpenClaw already installed ($(openclaw --version 2>/dev/null | head -1 || echo 'version unknown'))."
else
  say "Installing OpenClaw via the official installer (openclaw.ai/install.sh)…"
  curl -fsSL https://openclaw.ai/install.sh | bash
  hash -r 2>/dev/null || true
  if ! command -v openclaw >/dev/null 2>&1; then
    warn "openclaw is not on PATH in this shell yet — that's normal; open a new shell after this script finishes."
  fi
fi

# ---------------------------------------------------------------- 2. provider
PROVIDER="" KEY="" MODEL=""
if   [ -n "${XAI_API_KEY:-}" ];       then PROVIDER="xai";       KEY="$XAI_API_KEY"
elif [ -n "${ANTHROPIC_API_KEY:-}" ]; then PROVIDER="anthropic"
elif [ -n "${OPENAI_API_KEY:-}" ];    then PROVIDER="openai"
else
  echo
  say "Which model should power your bots?"
  echo "    1) xAI Grok   — grok-4.5 (the poetic choice: an open Grok Bot on the Grok API)"
  echo "    2) Anthropic  — claude-sonnet-4-6"
  echo "    3) OpenAI     — gpt-5.5"
  echo "    4) Skip       — I'll configure models myself (local/Ollama, other providers)"
  read -rp "  Choose [1-4]: " pick
  case "$pick" in
    1) PROVIDER="xai"
       read -rsp "  Paste your xAI API key (console.x.ai — input hidden): " KEY; echo
       [ -n "$KEY" ] || die "Empty key." ;;
    2) PROVIDER="anthropic" ;;
    3) PROVIDER="openai" ;;
    4) PROVIDER="skip" ;;
    *) die "Unknown choice: $pick" ;;
  esac
fi

case "$PROVIDER" in
  xai)       MODEL="xai/grok-4.5" ;;
  anthropic) MODEL="anthropic/claude-sonnet-4-6" ;;
  openai)    MODEL="openai/gpt-5.5" ;;
  skip)      MODEL="" ;;
esac
[ "$PROVIDER" = "skip" ] || say "Primary model: $MODEL"
if [ "$PROVIDER" = "anthropic" ] || [ "$PROVIDER" = "openai" ]; then
  say "$PROVIDER API auth is handled by 'openclaw onboard' (it verifies model access interactively)."
fi

# ---------------------------------------------------------------- 3. config
render_config() {
  # stdout: a complete openclaw.json (JSON5) for a fresh install
  cat <<HEADER
// Generated by OpenGrokBot setup.sh on $(date -u +%Y-%m-%dT%H:%MZ)
// Docs: https://docs.openclaw.ai/gateway/configuration
{
HEADER

  if [ "$PROVIDER" = "xai" ]; then
    cat <<'XAI'
  models: {
    providers: {
      // xAI is OpenAI-compatible; key lives here, on your disk, chmod 600.
      xai: {
        baseUrl: "https://api.x.ai/v1",
        apiKey: "__XAI_KEY__",
      },
    },
  },
XAI
  fi

  if [ -n "$MODEL" ]; then
    cat <<MODELBLOCK
  agents: {
    defaults: {
      model: { primary: "$MODEL" },
    },
MODELBLOCK
  else
    cat <<'MODELBLOCK'
  agents: {
    // No provider chosen — set your model here or during `openclaw onboard`.
    // defaults: { model: { primary: "provider/model" } },
MODELBLOCK
  fi

  cat <<'BODY'
    entries: {
      // Three teammates, Grok Bot-style: isolated workspace + memory each.
      researcher: {
        default: true,
        workspace: "~/.openclaw/workspace-researcher",
      },
      "inbox-keeper": {
        workspace: "~/.openclaw/workspace-inbox-keeper",
      },
      "market-watch": {
        workspace: "~/.openclaw/workspace-market-watch",
      },
    },
  },
  tools: {
    // The Grok Bot party trick: bots that message each other.
    // Explicit allowlist — remove any bot you don't want in the loop.
    agentToAgent: {
      enabled: true,
      allow: ["researcher", "inbox-keeper", "market-watch"],
    },
  },
  // Route channels to specific bots once you've connected them, e.g.:
  // bindings: [
  //   { agentId: "researcher",   match: { channel: "telegram" } },
  //   { agentId: "inbox-keeper", match: { channel: "slack" } },
  // ],
}
BODY
}

write_config_to() {
  local dest="$1"
  render_config >"$dest"
  if [ "$PROVIDER" = "xai" ]; then
    # inject the key without leaking it into process args
    KEY="$KEY" python3 - "$dest" <<'PY' 2>/dev/null || sed -i.bak "s|__XAI_KEY__|$KEY|" "$dest" && rm -f "$dest.bak"
import os, sys
p = sys.argv[1]
s = open(p).read().replace("__XAI_KEY__", os.environ["KEY"])
open(p, "w").write(s)
PY
  fi
  chmod 600 "$dest"
}

mkdir -p "$GEN_DIR"
if [ -f "$CONFIG" ]; then
  write_config_to "$GEN_DIR/openclaw.grokbot.json5"
  warn "Existing config found at $CONFIG — leaving it untouched."
  say  "Wrote $GEN_DIR/openclaw.grokbot.json5 instead."
  say  "Merge the models / agents / tools blocks into your config (guide: docs/multi-bot.md)."
else
  mkdir -p "$OC_DIR"
  write_config_to "$CONFIG"
  say "Wrote $CONFIG (chmod 600)."
fi

# ---------------------------------------------------------------- 4. teammates
for t in researcher inbox-keeper market-watch; do
  ws="$HOME/.openclaw/workspace-$t"
  mkdir -p "$ws/memory"
  for f in AGENTS.md SOUL.md; do
    if [ -f "$ws/$f" ]; then
      warn "Kept existing $ws/$f"
    else
      cp "$REPO_DIR/teammates/$t/$f" "$ws/$f"
      say "Installed $ws/$f"
    fi
  done
done

# ---------------------------------------------------------------- 5. next steps
echo
say "Assembly done. Next:"
echo
echo "    1. openclaw onboard --install-daemon    # first time: verifies model access, installs the daemon"
echo "       (already onboarded? restart the gateway instead so it picks up the new config)"
echo "    2. openclaw dashboard                   # Control UI — say hi to Scout"
echo "    3. Connect Telegram/WhatsApp/Slack:     https://docs.openclaw.ai/channels"
echo
say "Read docs/security.md before exposing anything to the internet."
say "Your bots. Your machine. \$0/month."
